# Generated by Django 4.2.3 on 2023-07-19 11:52

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_fave_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='fave_icon',
            field=models.ImageField(blank=True, default='', upload_to='assets/faveicon/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
